version: '3.5'

services:
    nginx:
        build: ./docker/nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ${HOME}:/var/www/
            - ./var/logs/nginx/:/var/log/nginx
            - ./docker/nginx/site:/etc/nginx/conf.d
            - ./docker/nginx/certs:/etc/certs
            - /var/run/php7-fpm/:/var/run/php7-fpm/
        networks:
            - common
            - lunchtime
    redis:
        image: redis:3.2.4-alpine
        ports:
            - 6379:6379
        volumes:
          - /var/data/redis:/data
        networks:
          common:
            aliases:
              - redis
    mongo:
        image: mongo:3.6
        ports:
            - 27017:27017
        environment:
            - MONGO_LOG_DIR=./var/logs/mongo
        volumes:
            - /var/data/mongo:/data/db
        networks:
          common:
            aliases:
              - mongo
    mysql:
        image: mysql:5.5.47
        ports:
          - 3306:3306
        volumes:
          - /var/data/mysql:/var/lib/mysql
        networks:
          common:
            aliases:
              - mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=dev
          - MYSQL_PASSWORD=dev
    myadmin:
      image: phpmyadmin/phpmyadmin:4.7
      environment:
        - PMA_HOST=mysql
      depends_on:
        - mysql
      ports:
        - 9008:80
      networks:
        - common
    elastic:
        build: ./docker/elastic
        ports:
            - 9200:9200
        volumes:
            - /var/data/elasticsearch:/usr/share/elasticsearch/data
        networks:
          common:
            aliases:
              - elastic
    front72:
        build: ./docker/front72
        image: front:7.2    
networks:
    common:
        driver: bridge
        name: common
    lunchtime:
        driver: bridge
        name: lunchtime        