version: '3.5'

services:
    nginx:
        restart: always
        build: ./docker/nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ${HOME}:/var/www/
            - ./var/logs/nginx/:/var/log/nginx
            - ./docker/nginx/site:/etc/nginx/conf.d
            - ./docker/nginx/certs:/etc/certs
            - /var/run/php7-fpm/:/var/run/php7-fpm/
        networks:
            - common
            - lunchtime
    redis:
        restart: always
        image: redis:3.2.4-alpine
        ports:
            - 6379:6379
        volumes:
          - /var/data/redis:/data
        networks:
          common:
            aliases:
              - redis
    mongo:
        restart: always
        image: mongo:4.2
        ports:
            - 27017:27017
        environment:
            - MONGO_LOG_DIR=./var/logs/mongo
        volumes:
            - /var/data/mongo:/data/db
        networks:
          common:
            aliases:
              - mongo
    mysql:
      image:  mariadb/server:10.4
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - /var/data/mariadb:/var/lib/mysql
      networks:
        common:
          aliases:
            - mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
    myadmin:
      restart: always
      image: phpmyadmin/phpmyadmin:4.7
      environment:
        - PMA_HOSTS=mysql,10.18.2.3,10.16.14.4,10.16.25.1
      volumes:
        - /home/dev/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      depends_on:
        - mysql
      ports:
        - 9008:80
      networks:
        - common
    elastic:
        restart: always
        build: ./docker/elastic
        ports:
            - 9200:9200
        volumes:
            - /var/data/elasticsearch:/usr/share/elasticsearch/data
        networks:
          common:
            aliases:
              - elastic
    front72:
        build: ./docker/front72
        image: front:7.2    
networks:
    common:
        driver: bridge
        name: common
    lunchtime:
        driver: bridge
        name: lunchtime        